blueprint:
  name: KNX - Alternating Percentage Sender v2024.01.7
  description: |
    This blueprint sends alternating 10% and 30% values to a specified KNX group address every 5 seconds using KNX data type 5.001.
  domain: automation
  input:
    knx_address:
      name: KNX Group Address
      description: The KNX group address to send the alternating values.
      selector:
        text:
    send_interval:
      name: Send Interval
      description: The interval in seconds to send the alternating values.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: seconds

mode: parallel
max_exceeded: silent

variables:
  knx_address: !input knx_address
  send_interval: !input send_interval
  current_value: 10

trigger:
  - platform: time_pattern
    seconds: "/{{ send_interval }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_value == 10 }}"
        sequence:
          - service: knx.send
            data:
              address: "{{ knx_address }}"
              payload: 30
              type: "percent"
          - variables:
              current_value: 30
      - conditions:
          - condition: template
            value_template: "{{ current_value == 30 }}"
        sequence:
          - service: knx.send
            data:
              address: "{{ knx_address }}"
              payload: 10
              type: "percent"
          - variables:
              current_value: 10
